# -*- coding: utf-8 -*-
"""Kvasir_Classification_meta_learners_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNZkdvYe2GRDMMa5byDO-X83ZHBJW285
"""

from google.colab import drive
import zipfile
import os

# 1. Mount Google Drive
drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/labeled-images.zip'

#    /content/ is the local disk of the Colab machine
extract_path = '/content/'

print("Unzipping dataset...")
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
print("Dataset unzipped successfully!")

data_dir = '/content/labeled-images'

if os.path.exists(data_dir):
    print(f"Dataset is ready at: {data_dir}")
else:
    print("Error: Dataset directory not found after unzipping.")

import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

# The path where you unzipped your data
data_dir = Path('/content/labeled-images')

# Walk through the directories to collect image paths and labels
image_paths = []
labels = []

# This loop finds all image files and uses their parent folder's name as the class label
for class_dir in data_dir.glob('**/*'):
    if class_dir.is_dir():
        for image_file in class_dir.glob('*.jpg'): # Adjust extension if needed (e.g., '*.png')
            image_paths.append(str(image_file))
            labels.append(class_dir.name)

# Create a DataFrame for easier handling
df = pd.DataFrame({'filepath': image_paths, 'label': labels})

print(f"Found {len(df)} images belonging to {len(df['label'].unique())} classes.")
print("\nClass distribution:")
print(df['label'].value_counts())

# Create a mapping from string labels to integer indices for the model
class_to_idx = {name: i for i, name in enumerate(df['label'].unique())}
idx_to_class = {i: name for name, i in class_to_idx.items()}
df['label_idx'] = df['label'].map(class_to_idx)

# Split the data: 80% train, 10% validation, 10% test
train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label_idx'])
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42, stratify=temp_df['label_idx'])

print(f"\nTraining set size: {len(train_df)}")
print(f"Validation set size: {len(val_df)}")
print(f"Test set size: {len(test_df)}")

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import gc # Garbage Collector interface

# --- 1. DATA LOADING SETUP (This part is unchanged) ---
class CustomImageDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.df = dataframe
        self.transform = transform
    def __len__(self):
        return len(self.df)
    def __getitem__(self, idx):
        img_path = self.df.iloc[idx]['filepath']
        label = self.df.iloc[idx]['label_idx']
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image, label

# Define transformations
# Note: EfficientNet-B6 is optimally trained on 528x528 images, but we'll use 224x224 for consistency.
IMG_SIZE = 224
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(IMG_SIZE),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),  # Adds random rotation
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1), # Adds color variations
    transforms.ToTensor(),
    normalize
])
val_test_transform = transforms.Compose([transforms.Resize(256), transforms.CenterCrop(IMG_SIZE), transforms.ToTensor(), normalize])
BATCH_SIZE = 32
train_dataset = CustomImageDataset(train_df, transform=train_transform)
val_dataset = CustomImageDataset(val_df, transform=val_test_transform)
test_dataset = CustomImageDataset(test_df, transform=val_test_transform)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
print("DataLoaders are ready.")

# --- 2. UPDATED MODEL DEFINITION HELPER ---
def get_model(model_name, num_classes, pretrained=True):
    model = None
    weights = 'DEFAULT' if pretrained else None

    # Load the base model
    if model_name == 'resnet50':
        model = models.resnet50(weights=weights)
    elif model_name == 'vgg16':
        model = models.vgg16(weights=weights)
    elif model_name == 'mobilenet_v2':
        model = models.mobilenet_v2(weights=weights)
    elif model_name == 'densenet121':
        model = models.densenet121(weights=weights)
    elif model_name == 'efficientnet_b6':
        model = models.efficientnet_b6(weights=weights)
    else:
        raise ValueError("Model name not recognized.")

    # Freeze all the base model parameters
    for param in model.parameters():
        param.requires_grad = False

    # --- UPDATED SECTION TO CORRECTLY REPLACE THE FINAL LAYER ---
    if model_name == 'resnet50':
        num_ftrs = model.fc.in_features
        model.fc = nn.Linear(num_ftrs, num_classes)

    elif model_name == 'vgg16':
        # VGG's classifier is a sequence. The last layer is at index 6.
        num_ftrs = model.classifier[6].in_features
        model.classifier[6] = nn.Linear(num_ftrs, num_classes)

    elif model_name == 'mobilenet_v2':
        # MobileNet's classifier is a sequence. The last layer is at index 1.
        num_ftrs = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(num_ftrs, num_classes)

    elif model_name == 'densenet121':
        # DenseNet's classifier is a single layer, so the original code works.
        num_ftrs = model.classifier.in_features
        model.classifier = nn.Linear(num_ftrs, num_classes)

    elif model_name == 'efficientnet_b6':
        # EfficientNet's classifier is a sequence. The last layer is at index 1.
        num_ftrs = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(num_ftrs, num_classes)

    return model

print("✅ get_model function has been updated to handle different model architectures.")

# --- 3. UPDATED MAIN VARIABLES ---
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
num_classes = len(df['label'].unique())
class_names = list(idx_to_class.values())

# --- CHANGE 2: ADD EFFICIENTNET-B6 TO THE LIST ---
models_to_train = ['resnet50', 'vgg16', 'mobilenet_v2', 'densenet121', 'efficientnet_b6']
results = {}
NUM_EPOCHS = 50
print("Setup complete. Ready to train:", models_to_train)

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import gc
import copy

# --- Specify the model to train and fine-tuning parameters ---
model_name = 'resnet50'
WARMUP_EPOCHS = 5
FINETUNE_EPOCHS = 25
TOTAL_EPOCHS = WARMUP_EPOCHS + FINETUNE_EPOCHS

# Learning Rates
# Use a standard LR for the head during warmup
LR_HEAD_WARMUP = 1e-3
# Use a very low LR for the unfrozen backbone layers
LR_BACKBONE_FINETUNE = 1e-5
# Use a low LR for the head during fine-tuning
LR_HEAD_FINETUNE = 1e-4


print(f"\n{'='*35}\n   Fine-Tuning Model: {model_name.upper()}\n{'='*35}")

# 1. Load the initial model (all base layers are frozen by get_model)
# (This requires get_model, num_classes, and device to be defined)
model = get_model(model_name, num_classes).to(device)
criterion = nn.CrossEntropyLoss()

# To keep track of the best model during training
best_val_acc = 0.0
best_model_wts = copy.deepcopy(model.state_dict())

# ==============================================================================
# STAGE 1: WARMUP - Train only the classifier head
# ==============================================================================
print(f"\n--- STAGE 1: WARMUP ({WARMUP_EPOCHS} Epochs) ---")
print("Training only the final classifier layer...")

# Optimizer for the head only
optimizer_head = optim.Adam(model.fc.parameters(), lr=LR_HEAD_WARMUP)

for epoch in range(WARMUP_EPOCHS):
    # --- Training Step ---
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_head.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_head.step()

    # --- Validation Step ---
    model.eval()
    val_loss = 0.0
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_loss += criterion(outputs, labels).item() * inputs.size(0)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Warmup complete.")


# ==============================================================================
# STAGE 2: UNFREEZE & FINE-TUNE
# ==============================================================================
print(f"\n--- STAGE 2: FINE-TUNING ({FINETUNE_EPOCHS} Epochs) ---")
print("Unfreezing the top layers (layer4) of the model...")

# Unfreeze the parameters of the last convolutional block
for param in model.layer4.parameters():
    param.requires_grad = True

# Create a new optimizer with different learning rates for different parts of the model
# This is the key to successful fine-tuning.
optimizer_finetune = optim.Adam([
    {'params': model.layer4.parameters(), 'lr': LR_BACKBONE_FINETUNE},
    {'params': model.fc.parameters(), 'lr': LR_HEAD_FINETUNE}
])

print("Starting full model fine-tuning...")
for epoch in range(FINETUNE_EPOCHS):
    # --- Training Step ---
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_finetune.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_finetune.step()

    # --- Validation Step ---
    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Fine-tuning complete.")


# ==============================================================================
# FINAL EVALUATION on the TEST SET
# ==============================================================================
print(f"\n--- Final Evaluation on Test Set ---")
print(f"Loading best model with validation accuracy: {best_val_acc:.4f}")
# Load the best model weights found during training
model.load_state_dict(best_model_wts)
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc=f"Evaluating {model_name}"):
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Display results
print(f"\n--- Classification Report for Fine-Tuned {model_name.upper()} ---\n")
print(classification_report(all_labels, all_preds, target_names=class_names))

print(f"\n--- Confusion Matrix for Fine-Tuned {model_name.upper()} ---\n")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Confusion Matrix for Fine-Tuned {model_name}')
plt.show()

# Save the best model's state to Google Drive
model_save_path = f'/content/drive/MyDrive/FineTunedModels/{model_name}_finetuned.pth'
torch.save(model.state_dict(), model_save_path)
print(f"✅ Best model state saved to {model_save_path}")

# Clean up memory
del model
del optimizer_head
del optimizer_finetune
gc.collect()
torch.cuda.empty_cache()

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import gc
import copy

# --- Specify the model to train and fine-tuning parameters ---
model_name = 'vgg16'
WARMUP_EPOCHS = 5
FINETUNE_EPOCHS = 25

# Learning Rates
LR_HEAD_WARMUP = 1e-3
LR_BACKBONE_FINETUNE = 1e-5
LR_HEAD_FINETUNE = 1e-4

print(f"\n{'='*35}\n   Fine-Tuning Model: {model_name.upper()}\n{'='*35}")

# 1. Load the initial model
model = get_model(model_name, num_classes).to(device)
criterion = nn.CrossEntropyLoss()
best_val_acc = 0.0
best_model_wts = copy.deepcopy(model.state_dict())

# ==============================================================================
# STAGE 1: WARMUP - Train only the classifier head
# ==============================================================================
print(f"\n--- STAGE 1: WARMUP ({WARMUP_EPOCHS} Epochs) ---")
print("Training only the final classifier layer...")

# Optimizer for the VGG classifier
optimizer_head = optim.Adam(model.classifier.parameters(), lr=LR_HEAD_WARMUP)

for epoch in range(WARMUP_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_head.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_head.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Warmup complete.")

# ==============================================================================
# STAGE 2: UNFREEZE & FINE-TUNE
# ==============================================================================
print(f"\n--- STAGE 2: FINE-TUNING ({FINETUNE_EPOCHS} Epochs) ---")
print("Unfreezing the top layers (last conv block) of the model...")

# Unfreeze the parameters of the last convolutional block in VGG16
for param in model.features[24:].parameters():
    param.requires_grad = True

# Create a new optimizer with different learning rates
optimizer_finetune = optim.Adam([
    {'params': model.features[24:].parameters(), 'lr': LR_BACKBONE_FINETUNE},
    {'params': model.classifier.parameters(), 'lr': LR_HEAD_FINETUNE}
])

print("Starting full model fine-tuning...")
for epoch in range(FINETUNE_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_finetune.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_finetune.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Fine-tuning complete.")

# ==============================================================================
# FINAL EVALUATION on the TEST SET
# ==============================================================================
print(f"\n--- Final Evaluation on Test Set ---")
print(f"Loading best model with validation accuracy: {best_val_acc:.4f}")
model.load_state_dict(best_model_wts)
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc=f"Evaluating {model_name}"):
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(f"\n--- Classification Report for Fine-Tuned {model_name.upper()} ---\n")
print(classification_report(all_labels, all_preds, target_names=class_names))

print(f"\n--- Confusion Matrix for Fine-Tuned {model_name.upper()} ---\n")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Confusion Matrix for Fine-Tuned {model_name}')
plt.show()

# Save the best model's state to Google Drive
model_save_path = f'/content/drive/MyDrive/FineTunedModels/{model_name}_finetuned.pth'
torch.save(model.state_dict(), model_save_path)
print(f"✅ Best model state saved to {model_save_path}")

# Clean up memory
del model
del optimizer_head
del optimizer_finetune
del best_model_wts
gc.collect()
torch.cuda.empty_cache()

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import gc
import copy

# --- Specify the model to train and fine-tuning parameters ---
model_name = 'mobilenet_v2'
WARMUP_EPOCHS = 5
FINETUNE_EPOCHS = 25

# Learning Rates
LR_HEAD_WARMUP = 1e-3
LR_BACKBONE_FINETUNE = 1e-5
LR_HEAD_FINETUNE = 1e-4

print(f"\n{'='*35}\n   Fine-Tuning Model: {model_name.upper()}\n{'='*35}")

# 1. Load the initial model
model = get_model(model_name, num_classes).to(device)
criterion = nn.CrossEntropyLoss()
best_val_acc = 0.0
best_model_wts = copy.deepcopy(model.state_dict())

# ==============================================================================
# STAGE 1: WARMUP - Train only the classifier head
# ==============================================================================
print(f"\n--- STAGE 1: WARMUP ({WARMUP_EPOCHS} Epochs) ---")
print("Training only the final classifier layer...")

# Optimizer for the MobileNetV2 classifier
optimizer_head = optim.Adam(model.classifier.parameters(), lr=LR_HEAD_WARMUP)

for epoch in range(WARMUP_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_head.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_head.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Warmup complete.")

# ==============================================================================
# STAGE 2: UNFREEZE & FINE-TUNE
# ==============================================================================
print(f"\n--- STAGE 2: FINE-TUNING ({FINETUNE_EPOCHS} Epochs) ---")
print("Unfreezing the top layers (last few blocks) of the model...")

# Unfreeze the parameters of the last few blocks in MobileNetV2
for param in model.features[14:].parameters():
    param.requires_grad = True

# Create a new optimizer with different learning rates
optimizer_finetune = optim.Adam([
    {'params': model.features[14:].parameters(), 'lr': LR_BACKBONE_FINETUNE},
    {'params': model.classifier.parameters(), 'lr': LR_HEAD_FINETUNE}
])

print("Starting full model fine-tuning...")
for epoch in range(FINETUNE_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_finetune.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_finetune.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Fine-tuning complete.")

# ==============================================================================
# FINAL EVALUATION on the TEST SET
# ==============================================================================
print(f"\n--- Final Evaluation on Test Set ---")
print(f"Loading best model with validation accuracy: {best_val_acc:.4f}")
model.load_state_dict(best_model_wts)
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc=f"Evaluating {model_name}"):
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(f"\n--- Classification Report for Fine-Tuned {model_name.upper()} ---\n")
print(classification_report(all_labels, all_preds, target_names=class_names))

print(f"\n--- Confusion Matrix for Fine-Tuned {model_name.upper()} ---\n")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Confusion Matrix for Fine-Tuned {model_name}')
plt.show()

# Save the best model's state to Google Drive
model_save_path = f'/content/drive/MyDrive/FineTunedModels/{model_name}_finetuned.pth'
torch.save(model.state_dict(), model_save_path)
print(f"✅ Best model state saved to {model_save_path}")

# Clean up memory
del model
del optimizer_head
del optimizer_finetune
del best_model_wts
gc.collect()
torch.cuda.empty_cache()

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import gc
import copy

# --- Specify the model to train and fine-tuning parameters ---
model_name = 'densenet121'
WARMUP_EPOCHS = 5
FINETUNE_EPOCHS = 25

# Learning Rates
LR_HEAD_WARMUP = 1e-3
LR_BACKBONE_FINETUNE = 1e-5
LR_HEAD_FINETUNE = 1e-4

print(f"\n{'='*35}\n   Fine-Tuning Model: {model_name.upper()}\n{'='*35}")

# 1. Load the initial model
model = get_model(model_name, num_classes).to(device)
criterion = nn.CrossEntropyLoss()

# To keep track of the best model during training
best_val_acc = 0.0
best_model_wts = copy.deepcopy(model.state_dict())

# ==============================================================================
# STAGE 1: WARMUP - Train only the classifier head
# ==============================================================================
print(f"\n--- STAGE 1: WARMUP ({WARMUP_EPOCHS} Epochs) ---")
print("Training only the final classifier layer...")

optimizer_head = optim.Adam(model.classifier.parameters(), lr=LR_HEAD_WARMUP)

for epoch in range(WARMUP_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_head.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_head.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Warmup complete.")

# ==============================================================================
# STAGE 2: UNFREEZE & FINE-TUNE
# ==============================================================================
print(f"\n--- STAGE 2: FINE-TUNING ({FINETUNE_EPOCHS} Epochs) ---")
print("Unfreezing the top layers (denseblock4) of the model...")

# Unfreeze the parameters of the last dense block
for param in model.features.denseblock4.parameters():
    param.requires_grad = True

optimizer_finetune = optim.Adam([
    {'params': model.features.denseblock4.parameters(), 'lr': LR_BACKBONE_FINETUNE},
    {'params': model.classifier.parameters(), 'lr': LR_HEAD_FINETUNE}
])

print("Starting full model fine-tuning...")
for epoch in range(FINETUNE_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_finetune.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_finetune.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Fine-tuning complete.")

# ==============================================================================
# FINAL EVALUATION on the TEST SET
# ==============================================================================
print(f"\n--- Final Evaluation on Test Set ---")
print(f"Loading best model with validation accuracy: {best_val_acc:.4f}")
model.load_state_dict(best_model_wts)
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc=f"Evaluating {model_name}"):
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(f"\n--- Classification Report for Fine-Tuned {model_name.upper()} ---\n")
print(classification_report(all_labels, all_preds, target_names=class_names))

print(f"\n--- Confusion Matrix for Fine-Tuned {model_name.upper()} ---\n")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Confusion Matrix for Fine-Tuned {model_name}')
plt.show()

model_save_path = f'/content/drive/MyDrive/FineTunedModels/{model_name}_finetuned.pth'
torch.save(model.state_dict(), model_save_path)
print(f"✅ Best model state saved to {model_save_path}")

del model, optimizer_head, optimizer_finetune
gc.collect()
torch.cuda.empty_cache()

import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
import gc
import copy

# --- Specify the model to train and fine-tuning parameters ---
model_name = 'efficientnet_b6'
WARMUP_EPOCHS = 10
FINETUNE_EPOCHS = 25

# Learning Rates
LR_HEAD_WARMUP = 1e-3
LR_BACKBONE_FINETUNE = 1e-5
LR_HEAD_FINETUNE = 1e-4

print(f"\n{'='*35}\n   Fine-Tuning Model: {model_name.upper()}\n{'='*35}")

# 1. Load the initial model
model = get_model(model_name, num_classes).to(device)
criterion = nn.CrossEntropyLoss()

# To keep track of the best model during training
best_val_acc = 0.0
best_model_wts = copy.deepcopy(model.state_dict())

# ==============================================================================
# STAGE 1: WARMUP - Train only the classifier head
# ==============================================================================
print(f"\n--- STAGE 1: WARMUP ({WARMUP_EPOCHS} Epochs) ---")
print("Training only the final classifier layer...")

optimizer_head = optim.Adam(model.classifier.parameters(), lr=LR_HEAD_WARMUP)

for epoch in range(WARMUP_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_head.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_head.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Warmup Epoch {epoch+1}/{WARMUP_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Warmup complete.")

# ==============================================================================
# STAGE 2: UNFREEZE & FINE-TUNE
# ==============================================================================
print(f"\n--- STAGE 2: FINE-TUNING ({FINETUNE_EPOCHS} Epochs) ---")
print("Unfreezing the top layers (last feature block) of the model...")

# Unfreeze the parameters of the last feature block in EfficientNet
for param in model.features[8].parameters():
    param.requires_grad = True

optimizer_finetune = optim.Adam([
    {'params': model.features[8].parameters(), 'lr': LR_BACKBONE_FINETUNE},
    {'params': model.classifier.parameters(), 'lr': LR_HEAD_FINETUNE}
])

print("Starting full model fine-tuning...")
for epoch in range(FINETUNE_EPOCHS):
    model.train()
    for inputs, labels in tqdm(train_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Train]"):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer_finetune.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_finetune.step()

    model.eval()
    val_corrects = 0
    with torch.no_grad():
        for inputs, labels in tqdm(val_loader, desc=f"Finetune Epoch {epoch+1}/{FINETUNE_EPOCHS} [Val]"):
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            val_corrects += torch.sum(preds == labels.data)

    epoch_acc = val_corrects.double() / len(val_dataset)
    print(f"Validation Accuracy: {epoch_acc:.4f}")

    if epoch_acc > best_val_acc:
        best_val_acc = epoch_acc
        best_model_wts = copy.deepcopy(model.state_dict())
        print("✅ New best model saved!")

print("\n✅ Fine-tuning complete.")

# ==============================================================================
# FINAL EVALUATION on the TEST SET
# ==============================================================================
print(f"\n--- Final Evaluation on Test Set ---")
print(f"Loading best model with validation accuracy: {best_val_acc:.4f}")
model.load_state_dict(best_model_wts)
model.eval()

all_preds, all_labels = [], []
with torch.no_grad():
    for inputs, labels in tqdm(test_loader, desc=f"Evaluating {model_name}"):
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(f"\n--- Classification Report for Fine-Tuned {model_name.upper()} ---\n")
print(classification_report(all_labels, all_preds, target_names=class_names))

print(f"\n--- Confusion Matrix for Fine-Tuned {model_name.upper()} ---\n")
cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title(f'Confusion Matrix for Fine-Tuned {model_name}')
plt.show()

model_save_path = f'/content/drive/MyDrive/FineTunedModels/{model_name}_finetuned.pth'
torch.save(model.state_dict(), model_save_path)
print(f"✅ Best model state saved to {model_save_path}")

del model, optimizer_head, optimizer_finetune
gc.collect()
torch.cuda.empty_cache()

import torch
import torch.nn.functional as F
from torchvision import models
import numpy as np
from tqdm import tqdm

# 1. List of trained models and paths
model_names = ['resnet50', 'vgg16', 'mobilenet_v2', 'densenet121', 'efficientnet_b6']
model_paths = {name: f'/content/drive/MyDrive/FineTunedModels/{name}_finetuned.pth' for name in model_names}

# 2. Reload models with the same architecture & classifier modifications
def load_trained_model(model_name, num_classes, device):
    model = get_model(model_name, num_classes, pretrained=False)  # don't need pretrained here
    model.load_state_dict(torch.load(model_paths[model_name], map_location=device))
    model.to(device)
    model.eval()
    return model

# Load all models into a list
ensemble_models = [load_trained_model(name, num_classes, device) for name in model_names]

print(f"✅ Loaded {len(ensemble_models)} models for ensemble.")

# 3. Ensemble Prediction Function (Soft Voting)
def ensemble_predict(models, dataloader, device):
    all_preds, all_labels = [], []

    with torch.no_grad():
        for inputs, labels in tqdm(dataloader, desc="Ensemble Inference"):
            inputs, labels = inputs.to(device), labels.to(device)

            # Collect probabilities from each model
            probs = []
            for model in models:
                outputs = model(inputs)
                probs.append(F.softmax(outputs, dim=1))  # convert to probabilities

            # Average probabilities
            avg_probs = torch.mean(torch.stack(probs), dim=0)

            # Get final predictions
            _, preds = torch.max(avg_probs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return np.array(all_labels), np.array(all_preds)

# 4. Run ensemble on test set
labels, preds = ensemble_predict(ensemble_models, test_loader, device)

# 5. Evaluate results
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

print("\n--- Ensemble Classification Report ---\n")
print(classification_report(labels, preds, target_names=class_names))

print("\n--- Ensemble Confusion Matrix ---\n")
cm = confusion_matrix(labels, preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Ensemble')
plt.show()

import torch
import torch.nn as nn
import numpy as np
from tqdm import tqdm

# --- 1. Define Model Names and Paths ---
# Ensure you have mounted your Google Drive
model_names = ['resnet50', 'vgg16', 'mobilenet_v2', 'densenet121', 'efficientnet_b6']
drive_folder = '/content/drive/MyDrive/FineTunedModels/' # Make sure this path is correct
model_paths = {name: f'{drive_folder}{name}_finetuned.pth' for name in model_names}

# --- 2. Load All Trained Base Models (Level 1) ---
# This list will hold your 5 trained "expert" models.
# The 'get_model', 'num_classes', and 'device' variables must be defined from your previous setup cells.
ensemble_models = []

print("Loading all 5 trained base models...")
for name in model_names:
    # Instantiate a new model with the correct architecture
    model = get_model(name, num_classes, pretrained=False)

    # Load the saved weights
    model.load_state_dict(torch.load(model_paths[name], map_location=device))

    # Move model to the GPU/CPU and set it to evaluation mode
    model.to(device)
    model.eval()

    ensemble_models.append(model)

print(f"✅ Successfully loaded {len(ensemble_models)} base models for Level 1.")

import torch.nn.functional as F
import numpy as np

# This helper function will take a list of models and a dataloader,
# and return the predictions (probabilities) and true labels.
def get_oof_predictions(dataloader, models):
    # Deactivate gradients for performance
    with torch.no_grad():
        all_labels = []
        # Store predictions from each model in a separate list
        model_predictions = [[] for _ in models]

        for inputs, labels in tqdm(dataloader, desc="Generating Meta-Features"):
            inputs = inputs.to(device)
            all_labels.extend(labels.cpu().numpy())

            for i, model in enumerate(models):
                outputs = model(inputs)
                # We use softmax to get probabilities, which are more informative
                # for the meta-learner than simple class predictions.
                probabilities = F.softmax(outputs, dim=1)
                model_predictions[i].extend(probabilities.cpu().numpy())

    # Concatenate predictions from all models horizontally
    # From [[model1_preds], [model2_preds], ...] to a single numpy array
    meta_features = np.concatenate([np.array(p) for p in model_predictions], axis=1)
    return meta_features, np.array(all_labels)

# --- Generate the training set for the meta-learner (using the validation set) ---
print("Generating meta-features for the training phase (from validation data)...")
# The 'val_loader' variable must be defined from your setup cells
meta_X_train, meta_y_train = get_oof_predictions(val_loader, ensemble_models)

# --- Generate the test set for the meta-learner (using the test set) ---
print("\nGenerating meta-features for the final evaluation (from test data)...")
# The 'test_loader' variable must be defined from your setup cells
meta_X_test, meta_y_test = get_oof_predictions(test_loader, ensemble_models)

# Print the shape of our new datasets
# The number of features should be num_models * num_classes (5 * 12 = 60)
print(f"\nShape of the meta-learner training data (X): {meta_X_train.shape}")
print(f"Shape of the meta-learner training labels (y): {meta_y_train.shape}")
print(f"Shape of the meta-learner test data (X): {meta_X_test.shape}")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# --- 1. Train the Meta-Learner (Level 2 Model) ---
print("Training the meta-learner (Logistic Regression)...")
meta_learner = LogisticRegression(max_iter=1000, C=1.0, solver='liblinear')
meta_learner.fit(meta_X_train, meta_y_train)
print("✅ Meta-learner trained successfully.")

# --- 2. Evaluate the Stacking Ensemble ---
print("\nEvaluating the complete stacking ensemble on the test set...")
final_predictions = meta_learner.predict(meta_X_test)

# --- 3. Display Final Results ---
print("\n" + "="*50)
print("      STACKING ENSEMBLE FINAL RESULTS (LEVEL 2)")
print("="*50 + "\n")

print("--- Stacking Classification Report ---\n")
# The 'class_names' variable must be defined from your setup cells
print(classification_report(meta_y_test, final_predictions, target_names=class_names))

print("\n--- Stacking Confusion Matrix ---\n")
cm = confusion_matrix(meta_y_test, final_predictions)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='viridis',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label (by Meta-Learner)')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Stacking Ensemble (Logistic Regression)')
plt.show()

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# --- 1. Train the Linear SVM Meta-Learner ---
print("Training the meta-learner (Linear SVM)...")
# SVC(kernel='linear') creates a Linear Support Vector Machine
meta_learner_svm = SVC(kernel='linear', random_state=42)
meta_learner_svm.fit(meta_X_train, meta_y_train)
print("✅ Meta-learner (SVM) trained successfully.")

# --- 2. Evaluate the Stacking Ensemble with SVM ---
print("\nEvaluating the stacking ensemble with SVM on the test set...")
final_predictions_svm = meta_learner_svm.predict(meta_X_test)

# --- 3. Display Final Results ---
print("\n--- Stacking Classification Report (SVM Meta-Learner) ---\n")
print(classification_report(meta_y_test, final_predictions_svm, target_names=class_names))

print("\n--- Stacking Confusion Matrix (SVM Meta-Learner) ---\n")
cm_svm = confusion_matrix(meta_y_test, final_predictions_svm)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_svm, annot=True, fmt='d', cmap='cividis',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label (by SVM Meta-Learner)')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Stacking Ensemble (SVM)')
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# --- 1. Train the KNN Meta-Learner ---
print("Training the meta-learner (K-Nearest Neighbors)...")
# n_neighbors=5 is a common starting point, but you can experiment with other values (e.g., 7, 9).
meta_learner_knn = KNeighborsClassifier(n_neighbors=7)
meta_learner_knn.fit(meta_X_train, meta_y_train)
print("✅ Meta-learner (KNN) trained successfully.")

# --- 2. Evaluate the Stacking Ensemble with KNN ---
print("\nEvaluating the stacking ensemble with KNN on the test set...")
final_predictions_knn = meta_learner_knn.predict(meta_X_test)

# --- 3. Display Final Results ---
print("\n--- Stacking Classification Report (KNN Meta-Learner) ---\n")
print(classification_report(meta_y_test, final_predictions_knn, target_names=class_names))

print("\n--- Stacking Confusion Matrix (KNN Meta-Learner) ---\n")
cm_knn = confusion_matrix(meta_y_test, final_predictions_knn)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_knn, annot=True, fmt='d', cmap='plasma',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label (by KNN Meta-Learner)')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Stacking Ensemble (KNN)')
plt.show()

from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# --- 1. Scale the Meta-Features ---
# Neural networks work best when input features are scaled.
print("Scaling meta-features for the MLP...")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(meta_X_train)
X_test_scaled = scaler.transform(meta_X_test)

# --- 2. Train the MLP Meta-Learner ---
print("Training the meta-learner (Multi-layer Perceptron)...")
# A single hidden layer with 100 neurons is a good start.
# max_iter is increased to ensure the model has enough time to converge.
meta_learner_mlp = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500,
                                 activation='relu', solver='adam', random_state=42)
meta_learner_mlp.fit(X_train_scaled, meta_y_train)
print("✅ Meta-learner (MLP) trained successfully.")

# --- 3. Evaluate the Stacking Ensemble with MLP ---
print("\nEvaluating the stacking ensemble with MLP on the test set...")
final_predictions_mlp = meta_learner_mlp.predict(X_test_scaled)

# --- 4. Display Final Results ---
print("\n--- Stacking Classification Report (MLP Meta-Learner) ---\n")
print(classification_report(meta_y_test, final_predictions_mlp, target_names=class_names))

print("\n--- Stacking Confusion Matrix (MLP Meta-Learner) ---\n")
cm_mlp = confusion_matrix(meta_y_test, final_predictions_mlp)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_mlp, annot=True, fmt='d', cmap='magma',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label (by MLP Meta-Learner)')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Stacking Ensemble (MLP)')
plt.show()

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# --- 1. Train the XGBoost Meta-Learner ---
print("Training the meta-learner (XGBoost)...")
# XGBoost has many parameters to tune, but these are good defaults.
# It's a good idea to explicitly use the GPU if available in Colab for speed.
meta_learner_xgb = xgb.XGBClassifier(objective='multi:softprob',
                                     eval_metric='mlogloss',
                                     use_label_encoder=False,
                                     n_estimators=200,
                                     learning_rate=0.1,
                                     max_depth=3,
                                     random_state=42,
                                     tree_method='gpu_hist' if torch.cuda.is_available() else 'hist')

meta_learner_xgb.fit(meta_X_train, meta_y_train)
print("✅ Meta-learner (XGBoost) trained successfully.")

# --- 2. Evaluate the Stacking Ensemble with XGBoost ---
print("\nEvaluating the stacking ensemble with XGBoost on the test set...")
final_predictions_xgb = meta_learner_xgb.predict(meta_X_test)

# --- 3. Display Final Results ---
print("\n--- Stacking Classification Report (XGBoost Meta-Learner) ---\n")
print(classification_report(meta_y_test, final_predictions_xgb, target_names=class_names))

print("\n--- Stacking Confusion Matrix (XGBoost Meta-Learner) ---\n")
cm_xgb = confusion_matrix(meta_y_test, final_predictions_xgb)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='inferno',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label (by XGBoost Meta-Learner)')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Stacking Ensemble (XGBoost)')
plt.show()

"""**WEIGHTED ENSEMBLING**"""

import torch
import torch.nn.functional as F
import numpy as np
from tqdm import tqdm
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ==============================================================================
# STEP 1: DEFINE YOUR MODEL ACCURACIES
# ==============================================================================
# These are the accuracies you provided for your fine-tuned models.
model_accuracies = {
    'resnet50': 0.94,
    'vgg16': 0.89,
    'mobilenet_v2': 0.92,
    'densenet121': 0.91,
    'efficientnet_b6': 0.83,
}

model_names = ['resnet50', 'vgg16', 'mobilenet_v2', 'densenet121', 'efficientnet_b6']

# ==============================================================================
# STEP 2: CALCULATE THE WEIGHTS
# ==============================================================================
# Get accuracies in the correct order
accuracies = [model_accuracies[name] for name in model_names]

# Calculate the sum of accuracies for normalization
total_accuracy = sum(accuracies)

# Calculate the weight for each model
weights = [acc / total_accuracy for acc in accuracies]

print("--- Calculated Ensemble Weights ---")
for name, weight in zip(model_names, weights):
    print(f"{name:<15}: {weight:.4f} ({weight:.1%})")
print("-----------------------------------")


# ==============================================================================
# STEP 3: LOAD MODELS AND PERFORM WEIGHTED INFERENCE
# ==============================================================================
# Ensure this path matches where your fine-tuned models are saved
model_paths = {name: f'/content/drive/MyDrive/FineTunedModels/{name}_finetuned.pth' for name in model_names}

def load_trained_model(model_name, num_classes, device):
    # Ensure get_model, num_classes are defined from your setup cells
    model = get_model(model_name, num_classes, pretrained=False)
    model.load_state_dict(torch.load(model_paths[model_name], map_location=device))
    model.to(device)
    model.eval()
    return model

# Load all models into a list
ensemble_models = [load_trained_model(name, num_classes, device) for name in model_names]
print(f"\n✅ Loaded {len(ensemble_models)} fine-tuned models.")

# Convert weights to a PyTorch tensor for calculations
weights_tensor = torch.tensor(weights, device=device).view(-1, 1, 1)

def weighted_ensemble_predict(models, weights, dataloader, device):
    all_preds, all_labels = [], []
    with torch.no_grad():
        for inputs, labels in tqdm(dataloader, desc="Weighted Ensemble Inference"):
            inputs, labels = inputs.to(device), labels.to(device)

            # Collect probabilities from each model and stack them
            # Resulting shape: [num_models, batch_size, num_classes]
            probs = torch.stack([F.softmax(model(inputs), dim=1) for model in models])

            # Perform the weighted sum of probabilities
            # This multiplies each model's probability output by its weight and sums them up
            weighted_probs = torch.sum(probs * weights, dim=0)

            # Get final predictions from the weighted probabilities
            _, preds = torch.max(weighted_probs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return np.array(all_labels), np.array(all_preds)

# Run weighted ensemble on the test set
# Ensure test_loader is defined from your setup cells
labels, preds = weighted_ensemble_predict(ensemble_models, weights_tensor, test_loader, device)


# ==============================================================================
# STEP 4: EVALUATE RESULTS
# ==============================================================================
print("\n--- Weighted Ensemble Classification Report ---\n")
# Ensure class_names is defined from your setup cells
print(classification_report(labels, preds, target_names=class_names))

print("\n--- Weighted Ensemble Confusion Matrix ---\n")
cm = confusion_matrix(labels, preds)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix - Weighted Ensemble')
plt.show()